services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/var/lib/redis/data
    environment:
      REDIS_USER: ${REDIS_USER}

  elastic:
    image: elasticsearch:7.17.22
    container_name: elastic
    env_file:
      - .env
    restart: always
    volumes:
      - elastic_data:/var/lib/elastic/data
    ports:
      - "9200:9200"
    environment:
      discovery.type: "single-node"

volumes:
  postgres_data:
  redis_data:
  elastic_data:
