"""update user model

Revision ID: 456a4ed26f50
Revises: a4f0a37dc67f
Create Date: 2025-05-02 00:18:15.342073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '456a4ed26f50'
down_revision: Union[str, None] = 'a4f0a37dc67f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birthday', sa.DateTime(), nullable=True, comment='Дата рождения'))
    op.add_column('user', sa.Column('email', sa.String(), nullable=False, comment='Почта'))
    op.add_column('user', sa.Column('username', sa.String(), nullable=False, comment='Имя пользователя'))
    op.add_column('user', sa.Column('password', sa.String(), nullable=False, comment='Пароль'))
    op.add_column('user', sa.Column('deleted', sa.Boolean(), nullable=False, comment='Удален ли пользователь'))
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(),
               comment='Имя',
               existing_nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(),
               comment='Фамилия',
               existing_nullable=False)
    op.alter_column('user', 'surname',
               existing_type=sa.VARCHAR(),
               comment='Отчество',
               existing_nullable=True)
    op.drop_column('user', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('user', 'surname',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Отчество',
               existing_nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Фамилия',
               existing_nullable=False)
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Имя',
               existing_nullable=False)
    op.drop_column('user', 'deleted')
    op.drop_column('user', 'password')
    op.drop_column('user', 'username')
    op.drop_column('user', 'email')
    op.drop_column('user', 'birthday')
    # ### end Alembic commands ###
